### ISSUE TITLE
Extension to 2D

### ISSUE THREAD

**Issue by Verlinch** [emadehsan/csp#1]
This is a fantastic solution, thank you for posting it. I was wondering, if you had any plans to upload your solution for 2D as well? Because i saw that you had the extension in the web version of CSP for rectangular sheets

**Comment by carbondriller** [comment]
Hey @Verlinch, thanks for reaching out :) 

I do have plans for posting 2D. But my [current implementation](https://alternate.parts/csp/) for 2D CSP is very naive. It doesn't cater many of the requirements, especially Guillotine cuts for Glass cutting. Also waste minimization is not really great in most cases.

I will post it here once I am satisfied with the results, hopefully in a few weeks :)

**Comment by emadehsan** [comment]
Hey @Verlinch, thanks for reaching out :)

I do have plans for posting 2D. But my current implementation for 2D CSP is very naive. It doesn't cater many of the requirements, especially Guillotine cuts for Glass cutting. Also waste minimization is not really great in most cases.

I will post it here once I am satisfied with the results, hopefully in a few weeks :)

**Comment by Verlinch** [comment]
Thank you! Id love to see how you tackle the 2D implementation, 1D works impressively. :)
