### ISSUE TITLE
Same problem, two different answers

### ISSUE THREAD

**Issue by ssteinerx** [emadehsan/csp#14]
I put in two problems, cut 4 18x36 pieces, or 4 36x18 pieces from a 48x96 sheet.

The program comes up with a different solution depending on the order of the dimensions on the pieces.

The graphics on the wrong one (Cut 1 below)are also wrong whereas the one on the correct answer (Cut 2 below) also is correct.

Swapping the dimensions of the sheet produces two *different* looking answers but, since the orientation of the sheet, and the outline of the remainder are not shown on the solution, it's hard telling whether the two answers are eqivalent.

![Cut 1 -- wrong](https://user-images.githubusercontent.com/43063/185795856-9692aae9-8b29-4251-a2bd-af5d75347807.png)
![Cut 2 -- right](https://user-images.githubusercontent.com/43063/185795859-dd749c44-e5da-4b34-a337-5e40c12c348b.png)

**Comment by emadehsan** [comment]
Hi @ssteinerx ,

Thank you for creating the issue. This repository has code only for 1D Cutting Stock Problem. Even though 2D CSP is available on website, it is an incorrect and incomplete implementation. That's why I didn't made the code public.

I didn't get the time to complete work on 2D version and as things stand right now, there is little hope that I would work on it anytime soon.

**Comment by 521bibi** [comment]
@emadehsan 
I understand that the 2d you are talking about is not perfect, but the functions are enough for me to learn and use. Could you open source the 2d solution for me to learn. I need it very much
Sincerely thank you for sharing

**Comment by emadehsan** [comment]
@521bibi I have added you to the private repository with code. Please check your inbox

**Comment by 521bibi** [comment]
> @521bibi我已将您添加到带有代码的私有存储库中。请检查您的收件箱

I see, thank you sincerely

**Comment by 521bibi** [comment]
> @521bibi I have added you to the private repository with code. Please check your inbox

I see, thank you sincerely

**Comment by ssteinerx** [comment]
@emadehsan I would be interested in the 2d code as well and may have some time.  Please add me as well.

**Comment by emadehsan** [comment]
@ssteinerx done.

**Comment by devourersouls** [comment]
@emadehsan Сould you give me access too? Very interesting to see the code. Thank you!

**Comment by emadehsan** [comment]
@devourersouls done.

**Comment by George-2022-7** [comment]
Could you open source the 2d solution for me to learn. I need it very much? Very interesting to see the code. Thank you very much!

**Comment by emadehsan** [comment]
@George-2022-7 I've to make a few edits before making it public. For the time being, I'm adding you to that private repo

**Comment by George-2022-7** [comment]
Thank you so much!!!!

**Comment by emadehsan** [comment]
I have added the code for [2-Dimensional CSP](https://github.com/emadehsan/csp#csp-2d) to this repository.
