### ISSUE TITLE
2d option

### ISSUE THREAD

**Issue by ajuricabense** [emadehsan/csp#4]
Does the option to cut 2d is public available?

**Comment by emadehsan** [comment]
Hi @ajuricabense 

I've not been able to work on 2d CSP because I've was not able to find a simple intuitive explanation for 2d CSP that actually covers all aspects while devising a solution.

If you are aware of any such explanation or implementation, do share. I'd appreciate that.

**Comment by ajuricabense** [comment]
@emadehsan I don't have an implementation, but I was thinking this http://dx.doi.org/10.1287/moor.25.4.645.12118 paper could be a suitable solution. 

Any updates I send to you. 
[kenyon2000.pdf](https://github.com/emadehsan/csp/files/6624367/kenyon2000.pdf)

**Comment by emadehsan** [comment]
@ajuricabense much thanks. Appreciated!

**Comment by emadehsan** [comment]
I have added the code for 2-Dimensional CSP to this repo. It is incomplete and inaccurate, but many students wanted to look at it:
https://github.com/emadehsan/csp#csp-2d
